# fly.toml file generated for serenity-dev on 2022-11-12T23:37:49+01:00

app = "serenity-dev"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[deploy]
  release_command = "yarn prisma:prod:migrate"

[env]
  PORT = "8080"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
  cmd = []
  entrypoint = []
  exec = []

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
