name: "Deploy API"

on:
  push:
    branches:
      - main

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        working-directory: ./apps/backend
        run: yarn build
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only ./apps/backend
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
